server:
  port: 8085

spring:
  application:
    name: demo

  r2dbc:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

    pool:
      enabled: true
      initial-size: 5
      max-size: 20

rapidapi:
  image-generator:
    base-url: ${RAPIAPI_URL}
    quick-path: ${RAPIAPI_QUICK_PAHT}
    host: ${RAPIAPI_HOST}
    api-key: ${RAPIAPI_API_KEY}
	
	
	