apiVersion: v1
kind: Secret
metadata:
  name: edy-beingolea-00-secret
  namespace: edy-beingolea-00-namespace
type: Opaque
data:
  DATABASE_URL: r2dbc:postgresql://ep-jolly-smoke-anvisuxe-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslMode=require
  DATABASE_USERNAME: neondb_owner
  DATABASE_PASSWORD: npg_fAq1Q3sWmiFl
  RAPIAPI_URL: https://ai-text-to-image-generator-flux-free-api.p.rapidapi.com
  RAPIAPI_QUICK_PAHT: /aaaaaaaaaaaaaaaaaiimagegenerator/quick.php
  RAPIAPI_HOST: ai-text-to-image-generator-flux-free-api.p.rapidapi.com
  RAPIAPI_API_KEY: 5d9117630fmsh219f0e2962d20e4p135537jsnfc0b2ca2bf66